theme: jekyll-theme-minimal

sidebar:
  - name: Installation
    link: /installation
  - name: Configuration
    link: /configuration
  - name: Usage - Default
    link: /usage
  - name: Usage - Vue
    link: /usage-vue
  - name: CSS Preprocessors
    link: /css-preprocessors
